plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }
    maven { url "https://maven.architectury.dev/" }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://maven.blamejared.com/"
    }
    maven {
        name "zigythebirdMods"
        url "https://maven.zigythebird.com/mods"
    }
    /*flatDir {
        dirs 'libs'
    }*/
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    //Player Animator
    modImplementation("dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}")
    include("dev.kosmx.player-anim:player-animation-lib-fabric:${project.player_anim}")
    //modImplementation files('libs/player-animation-lib-fabric-2.0.0+1.21.1.jar')

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${project.mixin_extras_ver}"))
    include("io.github.llamalad7:mixinextras-fabric:${project.mixin_extras_ver}:slim")

    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'

    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}");//ModMenu

    modApi("me.shedaniel.cloth:cloth-config-fabric:15.0.130") {
        exclude(group: "net.fabricmc.fabric-api")
    }
    modApi "dev.architectury:architectury-fabric:13.0.6"

    modCompileOnly("curse.maven:carry-on-274259:5541211") { transitive false }
    modCompileOnly("maven.modrinth:not-enough-animations:1.7.6")
    modCompileOnly("curse.maven:supplementaries-412082:5154524") { transitive false }
    modCompileOnly("curse.maven:sword-blocking-427738:5511755")
    modCompileOnly("maven.modrinth:oldcombatmod:0.1.4+1.21-fabric,1.21")
    modImplementation("com.zigythebird.playeranimatorapi:playeranimatorapi-fabric-1.21:2.2.1", {
        exclude group: "software.bernie.geckolib"
        exclude group: "com.github.Virtuoel"
        exclude group: "mod.azure.azurelib"
        exclude group: "com.eliotlash.mclib"
        exclude group: "net.fabricmc.fabric-api"
        exclude group: "maven.modrinth"
    })
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}