org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.configuration-cache=true

systemProp.neoforge.vineflower.args=--progress --threads 4
systemProp.neoforge.renamer.args=--progress

mod.id=cpa
mod.name=Custom Player Animations
mod.group=com.github.razorplay01
mod.version=5.1.0
mod.channel_tag=
mod.authors=RazorPlay01
mod.contributors=JarpPlay - Animations, ----------------------, McVader34 - Inspiration and ideas, Kelvin285 - Inspiration and ideas
mod.license=ARR
mod.description=Improves and customizes the player's default animations.
mod.sources_url=https://github.com/RazorPlay01/CPA
mod.homepage_url=https://github.com/RazorPlay01/CPA
mod.issues_url=https://github.com/RazorPlay01/CPA/issues
mod.discord_url=https://discord.gg/w5ECtBcz

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.cloth-config=[VERSIONED]
deps.player_animation_library=[VERSIONED]

publish.modrinth=EhthJpjM
publish.curseforge=1364067
publish.github=true
